# Generated by Django 2.2.9 on 2020-03-25 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_auto_20200325_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='room',
            field=models.ManyToManyField(blank=True, related_name='lists', to='rooms.Room'),
        ),
    ]
